# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener: true
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=2.0']
    serializer:
        serialize_null: true
#    allowed_methods_listener:  true
#    routing_loader: true
#    exception:
#        enabled: true
#        exception_controller: 'fos_rest.exception.controller:showAction'
#        codes:
#          { App\Exception\NotFoundException: 404 }
#        messages:
#          { App\Exception\NotFoundException: true }
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: 'json', priorities: [ 'json' ] }
